version: '3.9'

volumes: 
    coordinator_camera_database:

services:
    fastapi_app:
        build:
            context: .
            dockerfile: Dockerfile_app
        image: fastapi_app:latest

        user: root
        container_name: fastapi_app
        ports:
            - "4444:4444"
        volumes:
            - ./coordinator:/workspace/coordinator/
        labels:
            # Declare traefik routers
            - "traefik.enable=true"
            # - "traefik.http.routers.coordinator.rule=PathPrefix(`/api/xface/v1/coordinator`)"
            - "traefik.http.routers.coordinator.rule=PathPrefix(`/api/xface/v1/coordinator`)"
            - "traefik.http.routers.coordinator.entrypoints=web"
            - "traefik.http.routers.coordinator.service=coordinator-service"
            - "traefik.http.routers.coordinator.middlewares=strip-coordinator-prefix"
            - "traefik.http.middlewares.strip-coordinator-prefix.stripprefix.prefixes=/api/xface/v1/coordinator"
            # - "traefik.http.routers.coordinator.middlewares=authorization"
            
            # Declare traefik services
            - "traefik.http.services.coordinator-service.loadbalancer.server.port=${COORDINATOR_SERVICE_PORT:-4444}"
            # - "traefik.http.services.coordinator-service.loadbalancer.healthcheck.path=/"
            # - "traefik.http.services.coordinator-service.loadbalancer.healthcheck.interval=5s"
            # - "traefik.http.services.coordinator-service.loadbalancer.healthcheck.timeout=30s"
            # - "traefik.http.services.enterprise-service.loadbalancer.healthcheck.port=9031"

            # Declare traefik middlewares
            # - "traefik.http.middlewares.authorization.forwardauth.address=http://${ACCOUNT_SERVICE_CONTAINER_NAME:-account-service}:${ACCOUNT_SERVICE_PORT:-9031}/api/xface/v1/accounts/auth"
            # - "traefik.http.middlewares.authorization.forwardauth.trustForwardHeader=true"
        networks:
            - services-network

    coordinator:
        build:
            context: .
            dockerfile: Dockerfile_coordinator
        image: coordinator:latest

        user: root
        container_name: coordinator
        networks:
            - services-network
        volumes:
            - ./coordinator:/workspace/coordinator/

networks:
  services-network:
    external:
      name: ${COORDINATOR_SERVICES_NETWORK}
