FROM python:3.10.10

RUN mkdir -p ~/.config/pip && \
    echo \
    "[global]\n" \
    "no-cache-dir = true\n" \
    "trusted-host = 172.21.100.15\n" \
    "index = http://172.21.100.15:8081/repository/pypi-all/pypi\n" \
    "index-url = http://172.21.100.15:8081/repository/pypi-all/simple" \
    > ~/.config/pip/pip.conf

WORKDIR /workspace

COPY agent/requirements.txt agent/requirements.txt
RUN pip install --upgrade pip && pip install -r agent/requirements.txt
COPY agent/ agent/
COPY schemas/ schemas/

WORKDIR /workspace/agent/
ENV TZ Asia/Ho_Chi_Minh
CMD ["python", "agent.py"]
