version: '3.9'


services:
    coordinator:
        build:
            context: .
            dockerfile: Dockerfile_coordinator
        image: coordinator:latest

        user: root
        container_name: coordinator
        networks:
            coordinator-net:
                ipv4_address: 172.16.0.223
        ports:
          - "4444:4444"
networks:
    coordinator-net:
        ipam:
            config:
                - subnet: 172.16.0.0/24
